<!DOCTYPE html>
<html>
<head>
	<meta charset= "utf-8">
	<title> Fayth Kim </title>
	<link rel = "stylesheet" href = "css/style.css" />
</head>
<body>
<header>
<h1> Fayth Kim </h1>
<div id = "navContainer">
	<?php include('includes/nav.php');?>
</div>
</header>
<div id="bodyContainer">
<h1> About Me </h1>

	<h2>Previous and Current Jobs</h2>
 		<p>"I started working when I was 15. Babysitting was the first “job” that people have paid me for. It was usually for neighbors’ or family friends’ children that I would look after. Later, I became a lifeguard for my local pool and worked 2 summers there. From ages 17-19, I worked part-time at a golf course helping with the pro shop and teaching children how to golf. In addition, I tutored other students in math for some extra cash. Entering college, I immediately started working in some biochemistry labs as a lab aide at the University of Rochester Medical Center, helping with certain experiments and the daily preparation of different solutions/kits. Starting last summer, I began working as a research assistant in the microbiology department at the medical center. My research focused on hydrofracking and hydrofracking-related chemicals’ effects on antiviral and immunological responses. Xenopus laevis or African-clawed frogs were used as the model system. I love how the university has given me opportunities to expose myself to scientific research and even allow me to organize my own complicated experiments. It gives me a lot of independence and flexibility that I haven’t received from other jobs or opportunities. My PI, Jacques Robert, is also my major adviser and has mentored me throughout the entire process and has just helped me immensely. 
 		</p>

	<h2>Academic Background & Courses</h2>
		<p>Coming to the University of Rochester, I knew I wanted to get involved in the sciences. I switched between biochemistry or microbiology, but have decided that being a microbiology major was the best for me. In addition, I am pursuing computer science as well. This is all in the hopes that I can someday go to veterinary school. So far, I’ve taken many biology, chemistry, biochemistry, physics, computer science, philosophy, psychology, and genetics. My favorite classes I have taken would probably be some labs for my genetics or microbiology classes just because it’s always very involved and hands-on. I love it when stuff from textbooks can actually be related back to real-life situations or problems. By taking these various courses, I’ve learned information ranging from the philosophy of religion to the science of emerging pathogens. It’s nice having a wide variety of courses to take because it keeps learning fun for me. The last thing I would want is to get extremely bored or dread academia. I’m currently on the pre-med/pre-vet tract to hopefully go to veterinary school one day and open up my own clinic. I know the pain a pet owner feels when something is not right with their pet, so, it would be an honor to being able to help save, treat, or help that animal. Before I go to veterinary school however, I want to spend a gap year traveling and interning at various animal rehabilitation centers. There have been various programs all over the country, whether it be working with panda bears, endangered sea turtles, elephants, etc, that I am interested in. As an undergraduate student, I currently volunteer at Lollypop Farm, an animal humane society in greater Rochester. I help by working in the kennels, feeding or walking dogs, and on the farm, aiding to horses, goats, emus, and sheep. It’s a great experience even when it’s demanding because I get a lot of satisfaction from just helping. It is very hard for me to not want to take all the animals I work with home with me after my shifts. For those looking for another pet (mice, birds, turtles, chinchillas, dogs, cats, horses, sheep, goats, donkeys, pigs, emus, rabbits, frogs, etc), definitely check out Lollypop Farm in Victor, New York, you won’t regret it. And you’ll be saving a life!  
		</p>

	<h2>Other Interesting Facts About Me</h2>
		<p>Some other information about me is that I’m from Vernon Hills, IL, just outside of Chicago. My family consists of my mom, my dad, my 2 younger brothers, my obese wiener dog, my hamster, and my 2 turtles. Both of my parents are Korean and came to the United States when they were in their teens. When I was younger, I loved skateboarding and would hang out at the skatepark all the time, not caring if I was the only girl because I could do more tricks than all the other boys. This ambition eventually led to me badly spraining my ankle one summer. In highschool, I played basketball (I was the short point guard), golf, and lacrosse. Student council was also a big part of my highschool career, eventually becoming president. A random fact that most people would not know about me is that my dream job would have been to become a film maker or cinematographer. I’m a huge fan of Wes Anderson and his films, The Grand Budapest Hotel being my favorite. The process of setting up shots and editing videos to portray the perfect story sounds like the ideal life. I play 3 musical instruments: the piano (I re-taught myself after a 10-year hiatus), the cello (I started playing in 4th grade), the bass guitar (I may or may not have been in random bands throughout highschool and college),  and the guitar (I’m a huge fan of fingerstyle techniques). Another fact about me is that I started playing ultimate frisbee upon coming to college. My best friend Erik introduced me to the sport and encouraged me to try it, and here I am now, captaining the women’s team at the University of Rochester. The sport has completely revolutionized my life and I even played on summer club teams in Rochester and Chicago in the summers. Frisbee has allowed me to play and travel across the USA and even Canada. My favorite tournament that I’ve played in though would have to be Wildwood, a crazy beach tournament held in Wildwood, New Jersey during the summer. My friends, alum, and I made a team, drafted some cool jerseys, and had a blast playing frisbee and partying. For those who have never tried playing the sport, you should definitely give it a shot. You don’t have to be all that athletic, just need a few other friends and a disc (175g one to be specific). 
		</p>
</div>
</body>
</html>

